#!/usr/bin/env python3
"""Generate the block models and blockstates for every casino machine.

Two shapes, shared by every game, with proportions taken from the Discord bot's 3D casino
(activity/src/games/casino_experience: the station slot cabinet and the generic card table), scaled
to Minecraft's 16-unit block:

    tall cabinet   two blocks. Lower: a plinth and a body with a button deck sticking out at
                   waist height. Upper: the body again, its front set back 3/16 so the screen sits
                   in a recess between two light posts, under a full-width marquee topper.
    table          one block, 14/16 tall: a pedestal, a wooden rim, and a raised felt top.

Textures come from gen_casino_textures.py / gen_slot_textures.py and are mapped by position (no
explicit UVs), so the marquee picks up the gold band at the top of each upper-front texture and the
recess shows the screen below it.

TileEntityCasinoMachineRenderer draws each machine's screen on these faces, so two numbers here are
load-bearing there: the screen face is SCREEN_Z units from the front edge, and a table's felt is
FELT_TOP units high. Change either and change the renderer's offsets with it.

Writes src/main/resources/assets/lbe/models/block/<name>.json (and <name>_upper.json for tall
machines) and src/main/resources/assets/lbe/blockstates/<name>.json. Item models are separate cubes
and are not touched.

Usage (from the repo root):
    python tools/gen_casino_models.py
"""

import json
import os

ASSETS = os.path.join(os.path.dirname(__file__), "..", "src", "main", "resources", "assets", "lbe")

# name -> tall?
MACHINES = {
    "slot_machine": True,
    "coin_flip_table": False,
    "war_table": False,
    "high_low_machine": True,
    "roulette_table": False,
    "plinko_machine": True,
    "keno_machine": True,
    "baccarat_table": False,
    "video_poker_machine": True,
    "mines_machine": True,
}

# How far the upper body's screen face sits behind the front edge of the block, in 16ths. The
# renderer's tall-cabinet screen plane must match: (8 - SCREEN_Z) / 16 from the block centre.
SCREEN_Z = 4

# A table's felt height, in 16ths. The renderer draws table games at FELT_TOP / 16.
FELT_TOP = 14


def face(texture, cull=None):
    f = {"texture": "#" + texture}
    if cull:
        f["cullface"] = cull
    return f


def cuboid(frm, to, north="side", south="side", east="side", west="side", up="top",
           down="bottom", cull_down=False, cull_up=False):
    return {
        "from": frm,
        "to": to,
        "faces": {
            "north": face(north),
            "south": face(south),
            "east": face(east),
            "west": face(west),
            "up": face(up, "up" if cull_up else None),
            "down": face(down, "down" if cull_down else None),
        },
    }


def lower_cabinet():
    return [
        # Plinth: a dark base a little wider than the body, as on a real cabinet.
        cuboid([0.5, 0, 2], [15.5, 3, 16], north="bottom", south="bottom", east="bottom",
               west="bottom", up="bottom", cull_down=True),
        # Body, front face carrying the lower-front texture (coin tray, belly glass).
        cuboid([1, 3, 3], [15, 16, 15], north="front"),
        # Button deck: sticks out toward the player at waist height.
        cuboid([1.5, 9, 0.5], [14.5, 11, 3], north="side", up="top"),
    ]


def upper_cabinet():
    return [
        # Body with the screen recessed: its front face is the screen.
        cuboid([1, 0, SCREEN_Z], [15, 12, 15], north="front", up="top"),
        # Light posts either side of the screen, flush with the lower body's front.
        cuboid([1, 0, 3], [2, 12, SCREEN_Z], north="side"),
        cuboid([14, 0, 3], [15, 12, SCREEN_Z], north="side"),
        # Marquee topper: full width, overhanging the front. Its front shows the gold band.
        cuboid([0.5, 12, 2.5], [15.5, 16, 15.5], north="front", cull_up=False),
    ]


def table():
    return [
        # Pedestal.
        cuboid([3, 0, 3], [13, 11, 13], north="front", south="side", up="bottom",
               cull_down=True),
        # Wooden rim under the felt's edge.
        cuboid([0, 11, 0], [16, 13, 16], north="side", up="side"),
        # Felt, raised above the rim. Its top is the table's playing surface.
        cuboid([1, 13, 1], [15, FELT_TOP, 15], north="side", up="top"),
    ]


def model(elements, particle="front"):
    return {
        "__comment": "Generated by tools/gen_casino_models.py. Edit the script, not this file.",
        "parent": "block/block",
        "textures": {"particle": "#" + particle},
        "elements": elements,
    }


def textures(name, tall, upper):
    blocks = "lbe:blocks/" + name
    if name == "slot_machine":
        lower_front, lower_side = blocks + "_lower_front", blocks + "_lower_side"
    else:
        lower_front, lower_side = blocks + "_front", blocks + "_side"
    t = {"top": blocks + "_top", "bottom": blocks + "_bottom"}
    if tall and upper:
        t.update({"front": blocks + "_upper_front", "side": blocks + "_upper_side"})
    else:
        t.update({"front": lower_front, "side": lower_side})
    return t


def blockstate(name, tall):
    lower_model = "lbe:" + name
    upper_model = "lbe:" + name + "_upper" if tall else lower_model
    return {
        "__comment": "Generated by tools/gen_casino_models.py. forge_marker 1: the 'top' and "
                     "'facing' sets combine into every pairing. uvlock is false so the front "
                     "turns with the machine.",
        "forge_marker": 1,
        "defaults": {
            "model": lower_model,
            "textures": textures(name, tall, False),
            "uvlock": False,
        },
        "variants": {
            "top": {
                "false": {"model": lower_model, "textures": textures(name, tall, False)},
                "true": {"model": upper_model, "textures": textures(name, tall, True)},
            },
            "facing": {
                "north": {"y": 0},
                "south": {"y": 180},
                "west": {"y": 270},
                "east": {"y": 90},
            },
        },
    }


def write(path, data):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(data, indent=2, ensure_ascii=True) + "\n")


def leaderboard(name):
    # Two pixels deep against the wall behind it; its face is north before the blockstate turns
    # it. The renderer draws the lines 6/16 behind the block centre, on this face.
    return {
        "__comment": "Generated by tools/gen_casino_models.py. Edit the script, not this file.",
        "parent": "block/block",
        "textures": {
            "particle": "lbe:blocks/%s_side" % name,
            "front": "lbe:blocks/%s_front" % name,
            "side": "lbe:blocks/%s_side" % name,
        },
        "elements": [cuboid([0, 0, 14], [16, 16, 16], north="front", up="side", down="side")],
    }


def leaderboard_state(name):
    return {
        "__comment": "Generated by tools/gen_casino_models.py. 'facing' is the way the board's "
                     "face looks, away from the wall it hangs on.",
        "forge_marker": 1,
        "defaults": {"model": "lbe:" + name, "uvlock": False},
        "variants": {
            "facing": {
                "north": {"y": 0},
                "south": {"y": 180},
                "west": {"y": 270},
                "east": {"y": 90},
            },
            "inventory": [{}],
        },
    }


def main():
    models = os.path.join(ASSETS, "models", "block")
    states = os.path.join(ASSETS, "blockstates")
    for name, tall in MACHINES.items():
        if tall:
            write(os.path.join(models, name + ".json"), model(lower_cabinet()))
            write(os.path.join(models, name + "_upper.json"), model(upper_cabinet()))
        else:
            write(os.path.join(models, name + ".json"), model(table(), particle="top"))
        write(os.path.join(states, name + ".json"), blockstate(name, tall))
        print("wrote", name, "(%s)" % ("tall" if tall else "table"))
    for board in ("casino_leaderboard", "progressive_sign"):
        write_board(models, states, board)


def write_board(models, states, name):
    write(os.path.join(models, name + ".json"), leaderboard(name))
    write(os.path.join(states, name + ".json"), leaderboard_state(name))
    write(os.path.join(ASSETS, "models", "item", name + ".json"), {
        "__comment": "Generated by tools/gen_casino_models.py. Turned to show the face in a slot.",
        "parent": "lbe:block/" + name,
        "display": {
            "gui": {"rotation": [0, 180, 0], "translation": [0, 0, 0], "scale": [0.7, 0.7, 0.7]},
            "fixed": {"rotation": [0, 180, 0], "scale": [0.6, 0.6, 0.6]},
            "ground": {"rotation": [0, 0, 0], "translation": [0, 3, 0], "scale": [0.3, 0.3, 0.3]},
            "thirdperson_righthand": {"rotation": [75, 45, 0], "translation": [0, 2.5, 0],
                                      "scale": [0.375, 0.375, 0.375]},
            "firstperson_righthand": {"rotation": [0, 45, 0], "scale": [0.4, 0.4, 0.4]},
        },
    })
    print("wrote", name)


if __name__ == "__main__":
    main()
