#!/usr/bin/env python3
"""Generate the block models and blockstates for every casino machine.

Two shapes, shared by every game, with proportions taken from the Discord bot's 3D casino
(activity/src/games/casino_experience: the station slot cabinet and the generic card table), scaled
to Minecraft's 16-unit block:

    tall cabinet   two blocks. Lower: a plinth and a body with a button deck sticking out at
                   waist height. Upper: the body again, its front set back 3/16 so the screen sits
                   in a recess between two light posts, under a full-width marquee topper.
    table          one block, 14/16 tall: a pedestal, a wooden rim, and a raised felt top.

Textures come from gen_casino_textures.py / gen_slot_textures.py and are mapped by position (no
explicit UVs), so the marquee picks up the gold band at the top of each upper-front texture and the
recess shows the screen below it.

TileEntityCasinoMachineRenderer draws each machine's screen on these faces, so two numbers here are
load-bearing there: the screen face is SCREEN_Z units from the front edge, and a table's felt is
FELT_TOP units high. Change either and change the renderer's offsets with it.

Writes src/main/resources/assets/lbe/models/block/<name>.json (and <name>_upper.json for tall
machines) and src/main/resources/assets/lbe/blockstates/<name>.json. Item models are separate cubes
and are not touched.

Usage (from the repo root):
    python tools/gen_casino_models.py
"""

import json
import os

ASSETS = os.path.join(os.path.dirname(__file__), "..", "src", "main", "resources", "assets", "lbe")

# name -> tall?
MACHINES = {
    "slot_machine": True,
    "coin_flip_table": False,
    "war_table": False,
    "high_low_machine": True,
    "roulette_table": False,
    "plinko_machine": True,
    "keno_machine": True,
    "baccarat_table": False,
    "video_poker_machine": True,
    "mines_machine": True,
    "blackjack_table": False,
    "big_wheel": True,
    "pig_race": True,
    "craps_table": False,
}

# How far the upper body's screen face sits behind the front edge of the block, in 16ths. The
# renderer's tall-cabinet screen plane must match: (8 - SCREEN_Z) / 16 from the block centre.
SCREEN_Z = 4

# A table's felt height, in 16ths. The renderer draws table games at FELT_TOP / 16.
FELT_TOP = 14


def face(texture, cull=None):
    f = {"texture": "#" + texture}
    if cull:
        f["cullface"] = cull
    return f


def cuboid(frm, to, north="side", south="side", east="side", west="side", up="top",
           down="bottom", cull_down=False, cull_up=False):
    return {
        "from": frm,
        "to": to,
        "faces": {
            "north": face(north),
            "south": face(south),
            "east": face(east),
            "west": face(west),
            "up": face(up, "up" if cull_up else None),
            "down": face(down, "down" if cull_down else None),
        },
    }


def lower_cabinet():
    return [
        # Plinth: a dark base a little wider than the body, as on a real cabinet.
        cuboid([0.5, 0, 2], [15.5, 3, 16], north="bottom", south="bottom", east="bottom",
               west="bottom", up="bottom", cull_down=True),
        # Body, front face carrying the lower-front texture (coin tray, belly glass).
        cuboid([1, 3, 3], [15, 16, 15], north="front"),
        # Button deck: sticks out toward the player at waist height.
        cuboid([1.5, 9, 0.5], [14.5, 11, 3], north="side", up="top"),
    ]


def upper_cabinet():
    return [
        # Body with the screen recessed: its front face is the screen.
        cuboid([1, 0, SCREEN_Z], [15, 12, 15], north="front", up="top"),
        # Light posts either side of the screen, flush with the lower body's front.
        cuboid([1, 0, 3], [2, 12, SCREEN_Z], north="side"),
        cuboid([14, 0, 3], [15, 12, SCREEN_Z], north="side"),
        # Marquee topper: full width, overhanging the front. Its front shows the gold band.
        cuboid([0.5, 12, 2.5], [15.5, 16, 15.5], north="front", cull_up=False),
    ]


def table():
    return [
        # Pedestal.
        cuboid([3, 0, 3], [13, 11, 13], north="front", south="side", up="bottom",
               cull_down=True),
        # Wooden rim under the felt's edge.
        cuboid([0, 11, 0], [16, 13, 16], north="side", up="side"),
        # Felt, raised above the rim. Its top is the table's playing surface.
        cuboid([1, 13, 1], [15, FELT_TOP, 15], north="side", up="top"),
    ]


def model(elements, particle="front"):
    return {
        "__comment": "Generated by tools/gen_casino_models.py. Edit the script, not this file.",
        "parent": "block/block",
        "textures": {"particle": "#" + particle},
        "elements": elements,
    }


def textures(name, tall, upper):
    blocks = "lbe:blocks/" + name
    if name == "slot_machine":
        lower_front, lower_side = blocks + "_lower_front", blocks + "_lower_side"
    else:
        lower_front, lower_side = blocks + "_front", blocks + "_side"
    t = {"top": blocks + "_top", "bottom": blocks + "_bottom"}
    if tall and upper:
        t.update({"front": blocks + "_upper_front", "side": blocks + "_upper_side"})
    else:
        t.update({"front": lower_front, "side": lower_side})
    return t


def blockstate(name, tall):
    lower_model = "lbe:" + name
    upper_model = "lbe:" + name + "_upper" if tall else lower_model
    return {
        "__comment": "Generated by tools/gen_casino_models.py. forge_marker 1: the 'top' and "
                     "'facing' sets combine into every pairing. uvlock is false so the front "
                     "turns with the machine.",
        "forge_marker": 1,
        "defaults": {
            "model": lower_model,
            "textures": textures(name, tall, False),
            "uvlock": False,
        },
        "variants": {
            "top": {
                "false": {"model": lower_model, "textures": textures(name, tall, False)},
                "true": {"model": upper_model, "textures": textures(name, tall, True)},
            },
            "facing": {
                "north": {"y": 0},
                "south": {"y": 180},
                "west": {"y": 270},
                "east": {"y": 90},
            },
        },
    }


def write(path, data):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(data, indent=2, ensure_ascii=True) + "\n")


def leaderboard(name):
    # Two pixels deep against the wall behind it; its face is north before the blockstate turns
    # it. The renderer draws the lines 6/16 behind the block centre, on this face.
    return {
        "__comment": "Generated by tools/gen_casino_models.py. Edit the script, not this file.",
        "parent": "block/block",
        "textures": {
            "particle": "lbe:blocks/%s_side" % name,
            "front": "lbe:blocks/%s_front" % name,
            "side": "lbe:blocks/%s_side" % name,
        },
        "elements": [cuboid([0, 0, 14], [16, 16, 16], north="front", up="side", down="side")],
    }


def leaderboard_state(name):
    return {
        "__comment": "Generated by tools/gen_casino_models.py. 'facing' is the way the board's "
                     "face looks, away from the wall it hangs on.",
        "forge_marker": 1,
        "defaults": {"model": "lbe:" + name, "uvlock": False},
        "variants": {
            "facing": {
                "north": {"y": 0},
                "south": {"y": 180},
                "west": {"y": 270},
                "east": {"y": 90},
            },
            "inventory": [{}],
        },
    }


def vendor():
    # A cabinet with a window recessed into its front: a panel below (the renderer writes the tier
    # and price on it, 6/16 in front of the centre), a lintel above, posts either side, and a lit
    # back wall 8/16 deeper. The renderer turns the box 4/16 behind the front face, in the recess.
    textures = {
        "particle": "lbe:blocks/loot_box_vendor_front",
        "front": "lbe:blocks/loot_box_vendor_front",
        "side": "lbe:blocks/loot_box_vendor_side",
        "top": "lbe:blocks/loot_box_vendor_top",
        "bottom": "lbe:blocks/loot_box_vendor_top",
        "window": "lbe:blocks/loot_box_vendor_window",
    }
    return {
        "__comment": "Generated by tools/gen_casino_models.py. Edit the script, not this file.",
        "parent": "block/block",
        "textures": textures,
        "elements": [
            cuboid([1, 0, 2], [15, 5, 15], north="front", cull_down=True),
            cuboid([1, 13, 2], [15, 16, 15], north="front"),
            cuboid([1, 5, 2], [3, 13, 15], north="front"),
            cuboid([13, 5, 2], [15, 13, 15], north="front"),
            cuboid([3, 5, 10], [13, 13, 15], north="window", up="window", down="window"),
        ],
    }


def simple(textures, elements):
    return {
        "__comment": "Generated by tools/gen_casino_models.py. Edit the script, not this file.",
        "parent": "block/block",
        "textures": textures,
        "elements": elements,
    }


def all_faces(frm, to, texture, cull_down=False):
    return cuboid(frm, to, north=texture, south=texture, east=texture, west=texture, up=texture,
                  down=texture, cull_down=cull_down)


def decor_models():
    """(model name, model) for the decor set. The rope post is multipart: a post, plus half a
    rope toward each neighbouring post; the neighbour draws the other half."""
    return [
        ("casino_carpet", simple({"particle": "lbe:blocks/casino_carpet",
                                  "carpet": "lbe:blocks/casino_carpet"},
                                 [all_faces([0, 0, 0], [16, 1, 16], "carpet", cull_down=True)])),
        ("casino_carpet_royal", simple({"particle": "lbe:blocks/casino_carpet_royal",
                                        "carpet": "lbe:blocks/casino_carpet_royal"},
                                       [all_faces([0, 0, 0], [16, 1, 16], "carpet",
                                                  cull_down=True)])),
        ("bar_stool", simple({"particle": "lbe:blocks/bar_stool_cushion",
                              "metal": "lbe:blocks/bar_stool_metal",
                              "cushion": "lbe:blocks/bar_stool_cushion"},
                             [all_faces([4, 0, 4], [12, 1, 12], "metal", cull_down=True),
                              all_faces([7, 1, 7], [9, 9, 9], "metal"),
                              all_faces([5, 8, 5], [11, 9, 11], "metal"),
                              all_faces([3, 9, 3], [13, 12, 13], "cushion")])),
        ("velvet_rope_post", simple({"particle": "lbe:blocks/velvet_rope_brass",
                                     "brass": "lbe:blocks/velvet_rope_brass"},
                                    [all_faces([5, 0, 5], [11, 1, 11], "brass", cull_down=True),
                                     all_faces([7, 1, 7], [9, 13, 9], "brass"),
                                     all_faces([6.5, 13, 6.5], [9.5, 15, 9.5], "brass")])),
        # Half a rope, from the post toward the north edge, sagging a pixel toward the middle.
        ("velvet_rope_side", simple({"particle": "lbe:blocks/velvet_rope",
                                     "rope": "lbe:blocks/velvet_rope"},
                                    [all_faces([7.5, 11, 5], [8.5, 12, 7], "rope"),
                                     all_faces([7.5, 10, 0], [8.5, 11, 5], "rope")])),
    ]


def single_state(name):
    return {"forge_marker": 1, "defaults": {"model": "lbe:" + name},
            "variants": {"normal": [{}], "inventory": [{}]}}


def decor_states():
    post = {
        "__comment": "Generated by tools/gen_casino_models.py. Vanilla multipart: the post, and "
                     "half a rope toward each neighbouring post.",
        "multipart": [
            {"apply": {"model": "lbe:velvet_rope_post"}},
            {"when": {"north": "true"}, "apply": {"model": "lbe:velvet_rope_side"}},
            {"when": {"east": "true"}, "apply": {"model": "lbe:velvet_rope_side", "y": 90}},
            {"when": {"south": "true"}, "apply": {"model": "lbe:velvet_rope_side", "y": 180}},
            {"when": {"west": "true"}, "apply": {"model": "lbe:velvet_rope_side", "y": 270}},
        ],
    }
    return [("casino_carpet", single_state("casino_carpet")),
            ("casino_carpet_royal", single_state("casino_carpet_royal")),
            ("bar_stool", single_state("bar_stool")),
            ("velvet_rope_post", post)]


def main():
    models = os.path.join(ASSETS, "models", "block")
    states = os.path.join(ASSETS, "blockstates")
    for name, tall in MACHINES.items():
        if tall:
            write(os.path.join(models, name + ".json"), model(lower_cabinet()))
            write(os.path.join(models, name + "_upper.json"), model(upper_cabinet()))
        else:
            write(os.path.join(models, name + ".json"), model(table(), particle="top"))
        write(os.path.join(states, name + ".json"), blockstate(name, tall))
        print("wrote", name, "(%s)" % ("tall" if tall else "table"))
    for board in ("casino_leaderboard", "progressive_sign", "neon_sign"):
        write_board(models, states, board)
    for name, data in decor_models():
        write(os.path.join(models, name + ".json"), data)
    for name, data in decor_states():
        write(os.path.join(states, name + ".json"), data)
    for name in ("casino_carpet", "casino_carpet_royal", "bar_stool", "velvet_rope_post"):
        write(os.path.join(ASSETS, "models", "item", name + ".json"), {
            "__comment": "Generated by tools/gen_casino_models.py.",
            "parent": "lbe:block/" + name,
            "display": {
                "gui": {"rotation": [30, 225, 0], "translation": [0, 0, 0],
                        "scale": [0.625, 0.625, 0.625]},
                "ground": {"rotation": [0, 0, 0], "translation": [0, 3, 0],
                           "scale": [0.25, 0.25, 0.25]},
                "fixed": {"rotation": [0, 0, 0], "scale": [0.5, 0.5, 0.5]},
                "thirdperson_righthand": {"rotation": [75, 45, 0], "translation": [0, 2.5, 0],
                                          "scale": [0.375, 0.375, 0.375]},
                "firstperson_righthand": {"rotation": [0, 45, 0], "scale": [0.4, 0.4, 0.4]},
            },
        })
    print("wrote decor")
    write(os.path.join(models, "loot_box_vendor.json"), vendor())
    write(os.path.join(states, "loot_box_vendor.json"), {
        "__comment": "Generated by tools/gen_casino_models.py. 'facing' is the way the window looks.",
        "forge_marker": 1,
        "defaults": {"model": "lbe:loot_box_vendor", "uvlock": False},
        "variants": {
            "facing": {"north": {"y": 0}, "south": {"y": 180}, "west": {"y": 270},
                       "east": {"y": 90}},
            "inventory": [{}],
        },
    })
    write(os.path.join(ASSETS, "models", "item", "loot_box_vendor.json"), {
        "__comment": "Generated by tools/gen_casino_models.py.",
        "parent": "lbe:block/loot_box_vendor",
        "display": {
            "gui": {"rotation": [30, 225, 0], "translation": [0, 0, 0], "scale": [0.625, 0.625, 0.625]},
            "fixed": {"rotation": [0, 180, 0], "scale": [0.5, 0.5, 0.5]},
        },
    })
    print("wrote loot_box_vendor")


def write_board(models, states, name):
    write(os.path.join(models, name + ".json"), leaderboard(name))
    write(os.path.join(states, name + ".json"), leaderboard_state(name))
    write(os.path.join(ASSETS, "models", "item", name + ".json"), {
        "__comment": "Generated by tools/gen_casino_models.py. Turned to show the face in a slot.",
        "parent": "lbe:block/" + name,
        "display": {
            "gui": {"rotation": [0, 180, 0], "translation": [0, 0, 0], "scale": [0.7, 0.7, 0.7]},
            "fixed": {"rotation": [0, 180, 0], "scale": [0.6, 0.6, 0.6]},
            "ground": {"rotation": [0, 0, 0], "translation": [0, 3, 0], "scale": [0.3, 0.3, 0.3]},
            "thirdperson_righthand": {"rotation": [75, 45, 0], "translation": [0, 2.5, 0],
                                      "scale": [0.375, 0.375, 0.375]},
            "firstperson_righthand": {"rotation": [0, 45, 0], "scale": [0.4, 0.4, 0.4]},
        },
    })
    print("wrote", name)


if __name__ == "__main__":
    main()
